name: Validate

on:
  workflow_call:
    inputs:
      directory: 
        type: string
        default: ./website
        required: false
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Website
        working-directory: ${{ inputs.directory }}
        run: yarn --frozen-lockfile
      
      - name: Build website
        working-directory: ${{ inputs.directory }}
        run: yarn build